# ================================
# Golden Owl DevOps - CI/CD Workflow
# Author: hoangnguyen02
# ================================

name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_NAME }}/goldenowl-app
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

# ================================
# JOB 1: Build & Push Docker image
# ================================
jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t $DOCKER_IMAGE:latest .
          docker push $DOCKER_IMAGE:latest

# ================================
# JOB 2: Run Unit Tests
# ================================
  test:
    name: Run Node.js Tests
    runs-on: ubuntu-latest
    needs: build  # chỉ chạy sau khi build xong

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: src

      - name: Run tests
        run: npm test
        working-directory: src

# ================================
# JOB 3: Deploy to Google Cloud Run
# ================================
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    needs: [build, test]  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'gcloud'

      - name: Deploy App to Cloud Run
        run: |
          gcloud run deploy goldenowl-app \
            --image docker.io/hoangnguyen02/goldenowl-app:latest \
            --platform managed \
            --region us-west4 \
            --allow-unauthenticated
